version: '3.8'
services:
  db:
    image: mariadb:latest
    deploy:
      restart_policy:
        condition: any
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=Thiersee52
      - MYSQL_ROOT_PASSWORD=Thiersee52
      - MYSQL_PASSWORD=Thiersee52
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud

  phpmyadmin:
    image: phpmyadmin
    deploy:
      restart_policy:
        condition: any
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - nextcloud

  app:
    image: nextcloud:latest
    deploy:
      restart_policy:
        condition: any
    volumes:
      - nextcloud:/var/www/html
      - /mnt/shared_nvme/nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=Thiersee52
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - nextcloud

  web:
    image: nginx:latest
    deploy:
      restart_policy:
        condition: any
    ports:
      - 8080:80
    volumes:
      - /mnt/shared_nvme/nextcloud_data/docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html
    networks:
      - nextcloud

volumes:
  db:
  nextcloud:

networks:
  nextcloud:
    driver: overlay
