version: '3.8'
services:
  db:
    image: mariadb:10
    deploy:
      restart_policy:
        condition: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - nextcloud

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    deploy:
      restart_policy:
        condition: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_ARBITRARY: ${PMA_ARBITRARY}
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - nextcloud

  app:
    image: nextcloud:fpm
    deploy:
      restart_policy:
        condition: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      - /mnt/shared_nvme/nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
    networks:
      - nextcloud

  web:
    image: nginx:1
    deploy:
      restart_policy:
        condition: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html
      - /mnt/shared_nvme/nextcloud_data:/var/www/html/data
    networks:
      - nextcloud

volumes:
  db:
  nextcloud:

networks:
  nextcloud:
