version: '3.8'
services:
  db:
    image: mariadb:10
    deploy:
      restart_policy:
        condition: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Thiersee52
      - MYSQL_PASSWORD=Thiersee52
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    deploy:
      restart_policy:
        condition: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - nextcloud

  app:
    image: nextcloud:fpm
    deploy:
      restart_policy:
        condition: unless-stopped
    volumes:
      - nextcloud:/var/www/html
      - /mnt/shared_nvme/nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=Thiersee52
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - nextcloud

  web:
    image: nginx:1
    deploy:
      restart_policy:
        condition: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html
      - /mnt/shared_nvme/nextcloud_data:/var/www/html/data
    networks:
      - nextcloud

volumes:
  db:
  nextcloud:

networks:
  nextcloud:
